import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<body>
  <header className="border-b px-6 py-4">
    <nav className="flex gap-6 text-sm font-medium">
      <a href="/" className="hover:underline">Home</a>
      <a href="/pricing" className="hover:underline">Pricing</a>
      <a href="/mixer" className="hover:underline">Mixer</a>
    </nav>
  </header>

  <main>
    {children}
  </main>
</body>

  );
}
